site_name: Main Sequence SDK
nav:
  - Home: index.md
  - Examples: examples/index.md
  - TDAG:
      - Getting Started: tdag/getting_started.md
      - Time Series Data Pipelines Fundamentals: tdag/time_series_fundamentals.md
      - Orchestration & Monitoring: tdag/orchestration_and_monitoring.md
  - About: about.md
  - Reference: reference/



repo_url: https://github.com/mainsequence-sdk/mainsequence-sdk
edit_uri: edit/main/docs/

theme:
  name: "material"
  logo: "img/logo.png"
  favicon: "img/favico.ico" # Optional: Add a favicon
  palette:
    scheme: slate  # This makes dark mode the default scheme
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
    - navigation.tabs  # This enables navigation tabs for a better user experience
    - navigation.footer
    - navigation.indexes

plugins:
- search
- autorefs
- mermaid2
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [.]
        options:
          docstring_style: numpy
          heading_level: 3
          allow_inspection: false
          show_bases: true
          show_inheritance_diagram: true
          show_source: false
          show_root_heading: true


#for class inheritance
extra_javascript:
- https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

