[build-system]
requires = ["setuptools", "wheel","toml"]
build-backend = "setuptools.build_meta:__legacy__"

# PEP 621 dependencies declaration
# adapt to your dependencies manager
#[project]
#dependencies = [
#    "mkdocstrings-python",
#]