from __future__ import annotations

import datetime
from collections.abc import Mapping
from threading import RLock
from typing import TYPE_CHECKING, Any, ClassVar, Literal
from uuid import UUID

import pandas as pd
import yaml
from cachetools import TTLCache, cachedmethod
from pydantic import Field, SecretStr

from mainsequence.logconf import logger

from .base import (
    BaseObjectOrm,
    BasePydanticModel,
    CurrentCodeRepositoryBranchCollectionMixin,
    CurrentCodeRepositoryEnvironmentResourceMixin,
    LabelableObjectMixin,
    ShareableObjectMixin,
)
from .dtype_codec import (
    TIMESTAMP_TZ,
    token_to_pandas_series,
)
from .exceptions import raise_for_response
from .metatables import DataSource as _DataSource
from .utils import (
    make_request,
)

if TYPE_CHECKING:
    from .metatables import TimeIndexTableUpdate

_default_data_source = None  # Module-level cache

JSON_COMPRESSED_PREFIX = ["json_compressed", "jcomp_"]


class GitHubOrganization(BasePydanticModel, BaseObjectOrm):
    uid: str
    login: str
    display_name: str | None = None

    def __str__(self):
        return yaml.safe_dump(self.model_dump(), sort_keys=False, default_flow_style=False)


class CodeRepositoryBaseImage(BasePydanticModel, BaseObjectOrm):
    uid: str
    latest_digest: str | None = None
    digest: str | None = None
    catalog_ref: str | None = None
    catalog_role: str | None = None
    code_repository_type: str | None = None
    runtime: str | None = None
    is_default: bool | None = None
    pinned_image_uri: str | None = None
    description: str = ""
    title: str = ""
    tags: list[str] | None = None

    def __str__(self):
        return yaml.safe_dump(self.model_dump(), sort_keys=False, default_flow_style=False)


class CodeRepositoryNameValidationNormalized(BasePydanticModel):
    slugified_code_repository_name: str = Field(
        ...,
        title="Slugified CodeRepository Name",
        description="Slug-safe code repository name generated by the platform for URLs and repository naming.",
        examples=["rates-platform"],
        json_schema_extra={"label": "Slugified CodeRepository Name"},
    )
    repository_library_name: str = Field(
        ...,
        title="CodeRepository Library Name",
        description="Python-safe library/module name derived from the proposed code repository name.",
        examples=["rates_platform"],
        json_schema_extra={"label": "CodeRepository Library Name"},
    )


class CodeRepositoryNameValidationResult(BasePydanticModel):
    code_repository_name: str = Field(
        ...,
        title="CodeRepository Name",
        description="Original code repository name submitted for validation.",
        examples=["Rates Platform"],
        json_schema_extra={"label": "CodeRepository Name"},
    )
    available: bool = Field(
        ...,
        title="Available",
        description="Whether the code repository name is currently available for creation in the caller's organization.",
        examples=[False],
        json_schema_extra={"label": "Available"},
    )
    reason: str | None = Field(
        None,
        title="Reason",
        description="Human-readable explanation when the requested code repository name is unavailable or adjusted.",
        examples=["A code repository with this name already exists in your organization."],
        json_schema_extra={"label": "Reason"},
    )
    normalized: CodeRepositoryNameValidationNormalized = Field(
        ...,
        title="Normalized Names",
        description="Platform-generated normalized forms derived from the submitted code repository name.",
        json_schema_extra={"label": "Normalized Names"},
    )
    suggestions: list[str] = Field(
        default_factory=list,
        title="Suggestions",
        description="Alternative code repository names suggested by the platform when the submitted name is unavailable.",
        examples=[["Rates Platform 2", "Rates Platform 3", "Rates Platform 4"]],
        json_schema_extra={"label": "Suggestions"},
    )


class CodeRepositoryQuickSearchResult(BasePydanticModel):
    uid: str = Field(
        ...,
        title="UID",
        description="Public UID of the matching CodeRepository.",
        json_schema_extra={"label": "UID"},
    )
    code_repository_name: str = Field(
        ...,
        title="CodeRepository Name",
        description="Display name of the matching CodeRepository.",
        json_schema_extra={"label": "CodeRepository Name"},
    )
    code_repository_type: str = Field(
        ...,
        title="CodeRepository Type",
        description="Immutable type of the matching logical CodeRepository.",
        json_schema_extra={"label": "CodeRepository Type"},
    )


class CodeRepositoryBranchLight(BasePydanticModel):
    uid: str
    repository_branch: str


class CodeRepositorySDKObservation(BasePydanticModel):
    sdk_type: str
    package_name: str
    status: str
    version: str | None = None
    repository_path: str = ""
    observed_commit_sha: str = ""
    observed_at: datetime.datetime | None = None
    is_current: bool = False


class CodeRepositoryBulkDeleteResponse(BasePydanticModel):
    detail: str
    matched_count: int
    deleted_count: int


class CodeRepository(LabelableObjectMixin, ShareableObjectMixin, BasePydanticModel, BaseObjectOrm):
    FILTERSET_FIELDS: ClassVar[dict[str, list[str]]] = {
        "code_repository_name": ["in", "exact", "contains"],
        "code_repository_type": ["exact"],
        "uid": ["in", "exact"],
        "archived": ["exact"],
        "labels": ["exact", "in", "contains"],
    }
    FILTER_VALUE_NORMALIZERS: ClassVar[dict[str, str]] = {
        "uid": "str",
        "uid__in": "str",
        "code_repository_name": "str",
        "code_repository_type": "str",
        "archived": "bool",
        "labels": "str",
        "labels__in": "str",
        "labels__contains": "str",
    }
    uid: str = Field(
        ...,
        title="CodeRepository UID",
        description="Public UID of the CodeRepository.",
        examples=["code-repository-uid-142"],
        json_schema_extra={"label": "CodeRepository UID"},
    )
    code_repository_name: str = Field(
        ...,
        title="CodeRepository Name",
        description="Human-readable name of the CodeRepository.",
        examples=["Data Research Pipeline"],
        json_schema_extra={"label": "CodeRepository Name"},
    )
    code_repository_type: str = Field(
        ...,
        title="CodeRepository Type",
        description="Immutable type shared by every branch of this logical CodeRepository.",
        json_schema_extra={"label": "CodeRepository Type"},
    )
    primary_language: str = Field(
        ...,
        title="Primary Language",
        description="Read-only language projection derived from code_repository_type.",
        json_schema_extra={"label": "Primary Language"},
    )
    framework: str = Field(
        ...,
        title="Framework",
        description="Read-only framework projection derived from code_repository_type.",
        json_schema_extra={"label": "Framework"},
    )
    github_repository_binding_uid: str | None = None
    archived: bool = False
    created_by: str | int | dict[str, Any] | None = Field(
        None,
        title="Created By",
        description="Backend-provided creator metadata for the CodeRepository.",
        json_schema_extra={"label": "Created By"},
    )

    labels: list[str] = Field(
        default_factory=list,
        title="Labels",
        description=(
            "Organizational labels attached to the CodeRepository. "
            "These are helpers for grouping and discovery only and do not change runtime behavior or functionality."
        ),
        json_schema_extra={"label": "Labels"},
    )

    branches: list[CodeRepositoryBranchLight] = Field(default_factory=list)

    @staticmethod
    def _coerce_uid(obj: Any, *, field_name: str) -> str | None:
        """
        Accept:
          - None
          - uid string
          - any object with attribute `.uid`
          - dict-like with key "uid"
        """
        if obj is None:
            return None
        if isinstance(obj, UUID):
            return str(obj)
        if isinstance(obj, str):
            normalized = obj.strip()
            if normalized:
                return normalized
        if hasattr(obj, "uid") and obj.uid not in (None, ""):
            return str(obj.uid).strip()
        if isinstance(obj, dict) and obj.get("uid") not in (None, ""):
            return str(obj["uid"]).strip()
        raise TypeError(
            f"{field_name} must be a uid string, an object with .uid, a dict with 'uid', or None. "
            f"Got: {type(obj)!r}"
        )

    @classmethod
    def create(
        cls,
        *,
        code_repository_name: str,
        code_repository_type: str = "python",
        default_base_image_uid: str | CodeRepositoryBaseImage | dict[str, Any] | None = None,
        github_org_uid: str | GitHubOrganization | dict[str, Any] | None = None,
        bootstrap_organization_environment_uid: str | UUID | dict[str, Any] | BasePydanticModel | None = None,
        labels: list[str] | None = None,
        timeout: int | None = None,
    ) -> CodeRepository:
        """
        POST /code-repositories/

        Sends:
          - code_repository_name
          - code_repository_type
          - default_base_image_uid (optional)
          - github_org_uid (optional)
          - bootstrap_organization_environment_uid (optional active Environment UID)
        """
        url = cls.get_object_url() + "/"

        payload: dict[str, Any] = {"code_repository_name": code_repository_name, "code_repository_type": code_repository_type}

        img_uid = cls._coerce_uid(default_base_image_uid, field_name="default_base_image_uid")
        if img_uid is not None:
            payload["default_base_image_uid"] = img_uid

        org_uid = cls._coerce_uid(github_org_uid, field_name="github_org_uid")
        if org_uid is not None:
            payload["github_org_uid"] = org_uid

        bootstrap_environment_uid = cls._coerce_uid(
            bootstrap_organization_environment_uid,
            field_name="bootstrap_organization_environment_uid",
        )
        if bootstrap_environment_uid is not None:
            payload["bootstrap_organization_environment_uid"] = bootstrap_environment_uid
        if labels is not None:
            payload["labels"] = list(labels)

        s = cls.build_session()
        r = make_request(
            s=s,
            loaders=cls.LOADERS,
            r_type="POST",
            url=url,
            payload={"json": payload},
            time_out=timeout,
        )

        # your helpers already exist; use them consistently
        raise_for_response(r)

        # DRF should return 201 with your detail serializer shape
        return cls(**r.json())

    @classmethod
    def quick_search(
        cls,
        q: str,
        *,
        limit: int = 20,
        timeout: int | None = None,
    ) -> list[CodeRepositoryQuickSearchResult]:
        """
        Return CodeRepository quick-search matches visible to the authenticated user.

        This hits:
            GET /api/v1/code-repositories/quick-search/?q=...

        Parameters
        ----------
        q:
            Search query. Must contain at least 3 non-whitespace characters.
        limit:
            Maximum number of matches to return. Defaults to 20 and is capped at 100.
        timeout:
            Optional request timeout in seconds.
        """
        normalized_query = (q or "").strip()
        if len(normalized_query) < 3:
            raise ValueError("Query must contain at least 3 characters.")

        limit = int(limit)
        if limit < 1 or limit > 100:
            raise ValueError("limit must be between 1 and 100")

        url = cls.get_object_url() + "/quick-search/"
        r = make_request(
            s=cls.build_session(),
            loaders=cls.LOADERS,
            r_type="GET",
            url=url,
            payload={"params": {"q": normalized_query, "limit": limit}},
            time_out=timeout,
        )
        raise_for_response(r)

        if not r.content:
            return []

        payload = r.json()
        if not isinstance(payload, list):
            raise ValueError(
                f"Unexpected response type for CodeRepository.quick_search(): {type(payload)!r}"
            )

        return [CodeRepositoryQuickSearchResult.model_validate(item) for item in payload]

    @classmethod
    def validate_name(
        cls,
        *,
        code_repository_name: str,
        timeout: int | None = None,
    ) -> CodeRepositoryNameValidationResult:
        """
        Validate whether a code repository name is available for creation on the platform.

        This hits:
            GET /api/v1/code-repositories/validate-name/?code_repository_name=...

        Parameters
        ----------
        code_repository_name:
            Candidate code repository name to validate.
        timeout:
            Optional request timeout in seconds.

        Returns
        -------
        CodeRepositoryNameValidationResult
            Validation payload including availability, normalized names, and suggested alternatives.
        """
        normalized_code_repository_name = (code_repository_name or "").strip()
        if not normalized_code_repository_name:
            raise ValueError("code_repository_name is required.")

        url = cls.get_object_url() + "/validate-name/"
        r = make_request(
            s=cls.build_session(),
            loaders=cls.LOADERS,
            r_type="GET",
            url=url,
            payload={"params": {"code_repository_name": normalized_code_repository_name}},
            time_out=timeout,
        )
        raise_for_response(r)

        if not r.content:
            raise ValueError("CodeRepository.validate_name() returned an empty response.")

        payload = r.json()
        if not isinstance(payload, dict):
            raise ValueError(
                f"Unexpected response type for CodeRepository.validate_name(): {type(payload)!r}"
            )

        return CodeRepositoryNameValidationResult.model_validate(payload)

    @classmethod
    def bulk_delete(
        cls,
        *,
        uids: list[str] | None = None,
        selection: dict[str, Any] | None = None,
        timeout: int | None = None,
    ) -> CodeRepositoryBulkDeleteResponse:
        if (uids is None) == (selection is None):
            raise ValueError("Pass exactly one of uids or selection.")
        resolved_selection = selection or {"mode": "explicit", "uids": list(uids or [])}
        r = make_request(
            s=cls.build_session(),
            loaders=cls.LOADERS,
            r_type="POST",
            url=cls.get_object_url() + "/bulk-delete/",
            payload={
                "json": {
                    "selection": resolved_selection,
                    "options": {},
                }
            },
            time_out=timeout,
        )
        raise_for_response(r)
        return CodeRepositoryBulkDeleteResponse.model_validate(r.json())

    def add_deploy_key(self, *, key_title: str, public_key: str, timeout=None) -> None:
        """Register a repository deploy key through the owning CodeRepository."""
        r = make_request(
            s=type(self).build_session(),
            loaders=type(self).LOADERS,
            r_type="POST",
            url=(
                f"{type(self).get_object_url()}/{self._public_detail_reference()}/add-deploy-key/"
            ),
            payload={"json": {"key_title": key_title, "public_key": public_key}},
            time_out=timeout,
        )
        raise_for_response(r)

    def __str__(self):
        return yaml.safe_dump(
            self.model_dump(),
            sort_keys=False,
            default_flow_style=False,
        )


class CodeRepositoryBranch(BasePydanticModel, BaseObjectOrm):
    FILTERSET_FIELDS: ClassVar[dict[str, list[str]]] = {
        "uid": ["in", "exact"],
        "code_repository_uid": ["exact"],
        "code_repository_name": ["in", "exact", "contains"],
        "repository_branch": ["in", "exact", "contains"],
    }
    FILTER_VALUE_NORMALIZERS: ClassVar[dict[str, str]] = {
        "uid": "uid",
        "uid__in": "uid",
        "code_repository_uid": "uid",
        "code_repository_name": "str",
        "repository_branch": "str",
    }

    uid: str
    code_repository_uid: str
    code_repository_name: str
    code_repository_type: str = Field(
        ...,
        description=(
            "Read-only projection of the immutable type owned by the parent "
            "CodeRepository."
        ),
    )
    repository_branch: str
    metatables_data_source: _DataSource | None = None
    metatables_data_source_uid: str | None = None
    organization_environment_uid: str | None = None
    organization_environment_name: str | None = None
    default_base_image: CodeRepositoryBaseImage
    sdks: list[CodeRepositorySDKObservation] = Field(default_factory=list)
    github_repository_binding_uid: str | None = None
    latest_git_version: str = ""
    is_initialized: bool
    created_by: str | int | dict[str, Any] | None = None

    @classmethod
    def resolve_git_context(
        cls,
        *,
        repository_identity: str,
        repository_branch: str,
        commit_sha: str,
        timeout=None,
    ) -> CodeRepositoryBranchGitContextResolution:
        """Resolve the authenticated caller's exact Git source context."""

        payload = {
            "repository_identity": repository_identity,
            "repository_branch": repository_branch,
            "commit_sha": commit_sha,
        }
        response = make_request(
            s=cls.build_session(),
            loaders=cls.LOADERS,
            r_type="POST",
            url=f"{cls.get_object_url()}/resolve-git-context/",
            payload={"json": payload},
            time_out=timeout,
        )
        raise_for_response(response, payload=payload)
        return CodeRepositoryBranchGitContextResolution.model_validate(response.json())

    def _action_url(self, action: str) -> str:
        return (
            f"{type(self).get_object_url()}/{self._public_detail_reference()}/{action.strip('/')}/"
        )

    def _get_action(self, action: str, *, params=None, timeout=None) -> Any:
        r = make_request(
            s=type(self).build_session(),
            loaders=type(self).LOADERS,
            r_type="GET",
            url=self._action_url(action),
            payload={"params": params} if params else {},
            time_out=timeout,
        )
        raise_for_response(r)
        return r.json() if r.content else None

    def summary(self, *, timeout=None) -> dict[str, Any]:
        return self._get_action("summary", timeout=timeout)

    def browse_repository(self, path: str = "", *, timeout=None) -> dict[str, Any]:
        return self._get_action("browse-repository", params={"path": path}, timeout=timeout)

    def resource_code(self, path: str = "", *, timeout=None) -> dict[str, Any]:
        return self._get_action("resource-code", params={"path": path}, timeout=timeout)

    def infra_graph(self, *, commit_sha: str | None = None, timeout=None) -> dict[str, Any]:
        params = {"commit_sha": commit_sha} if commit_sha else None
        return self._get_action("infra-graph", params=params, timeout=timeout)

    def update_sdk(self, *, timeout=None) -> dict[str, Any]:
        r = make_request(
            s=type(self).build_session(),
            loaders=type(self).LOADERS,
            r_type="POST",
            url=self._action_url("update-sdk"),
            payload={"json": {}},
            time_out=timeout,
        )
        raise_for_response(r)
        return r.json()

    def get_time_index_table_updates(self, *, timeout: int | None = None) -> list[Any]:
        from .metatables import TimeIndexTableUpdate

        payload = self._get_action("get-time-index-table-updates", timeout=timeout)
        if isinstance(payload, list):
            raw_updates = payload
        elif isinstance(payload, dict):
            if "time_index_table_updates" in payload:
                raw_updates = payload["time_index_table_updates"]
            elif "results" in payload:
                raw_updates = payload["results"]
            else:
                raise ValueError(
                    "CodeRepositoryBranch time-index table update response requires "
                    "time_index_table_updates or results."
                )
        else:
            raise ValueError(
                "Unexpected response type for CodeRepositoryBranch time-index table updates: "
                f"{type(payload)!r}"
            )
        if not isinstance(raw_updates, list):
            raise ValueError("CodeRepositoryBranch time-index table updates must be a list.")
        return [
            update if isinstance(update, TimeIndexTableUpdate) else TimeIndexTableUpdate(**update)
            for update in raw_updates
        ]

    def __str__(self):
        return yaml.safe_dump(self.model_dump(), sort_keys=False, default_flow_style=False)


class CodeRepositoryBranchGitContextResolution(BasePydanticModel):
    canonical_repository_identity: str
    repository_branch: str
    repository_ref: str
    commit_sha: str
    code_repository_branch: CodeRepositoryBranch


class GitHubRepositoryBranch(BasePydanticModel):
    repository_branch: str
    head_sha: str
    is_linked: bool
    code_repository_branch_uid: str | None = None


class GitHubRepositoryBranchList(BasePydanticModel):
    repository_uid: str
    results: list[GitHubRepositoryBranch]


class GitHubRepositoryBranchImportResult(BasePydanticModel):
    repository_uid: str
    code_repository_branch_uid: str
    repository_branch: str
    is_initialized: bool


class GitHubRepositoryBinding(BasePydanticModel, BaseObjectOrm):
    FILTERSET_FIELDS: ClassVar[dict[str, list[str]]] = {
        "uid": ["in", "exact"],
        "code_repository_name": ["in", "exact", "contains"],
        "labels": ["exact", "in", "contains"],
    }
    uid: str
    code_repository_uid: str
    code_repository_name: str
    repo_name: str
    github_full_name: str
    git_ssh_url: str | None = None
    git_repo_url: str | None = None
    created_by: str | int | dict[str, Any] | None = None

    def branches(self, *, timeout=None) -> GitHubRepositoryBranchList:
        url = f"{type(self).get_object_url()}/{self._public_detail_reference()}/branches/"
        r = make_request(
            s=type(self).build_session(),
            loaders=type(self).LOADERS,
            r_type="GET",
            url=url,
            time_out=timeout,
        )
        raise_for_response(r)
        return GitHubRepositoryBranchList.model_validate(r.json())

    def import_branch(
        self,
        *,
        repository_branch: str,
        metatables_data_source_uid: str | None = None,
        timeout=None,
    ) -> GitHubRepositoryBranchImportResult:
        body: dict[str, Any] = {"repository_branch": repository_branch}
        if metatables_data_source_uid is not None:
            body["metatables_data_source_uid"] = str(metatables_data_source_uid)
        url = f"{type(self).get_object_url()}/{self._public_detail_reference()}/import-branch/"
        r = make_request(
            s=type(self).build_session(),
            loaders=type(self).LOADERS,
            r_type="POST",
            url=url,
            payload={"json": body},
            time_out=timeout,
        )
        raise_for_response(r)
        return GitHubRepositoryBranchImportResult.model_validate(r.json())


class CodeRepositoryImageSourceProvenance(BasePydanticModel):
    verification_state: Literal["verified", "unverified", "building", "failed"]
    code_repository_uid: str | None = None
    code_repository_branch_uid: str | None = None
    github_repository_binding_uid: str | None = None
    repository_branch: str | None = None
    repository_ref: str | None = None
    commit_sha: str | None = None
    source_archive_sha256: str | None = None
    build_context_checksum: str | None = None
    base_image_uid: str | None = None
    output_image_digest: str | None = None


class CodeRepositoryImage(CurrentCodeRepositoryBranchCollectionMixin, BasePydanticModel, BaseObjectOrm):
    """
    Image build from a code repository
    """

    FILTERSET_FIELDS: ClassVar[dict[str, list[str]]] = {
        "search": ["exact"],
        "related_code_repository_branch_uid": ["in", "exact"],
        "code_repository_commit_hash": ["exact", "in"],
    }
    FILTER_VALUE_NORMALIZERS: ClassVar[dict[str, str]] = {
        "related_code_repository_branch_uid": "uid",
        "related_code_repository_branch_uid__in": "uid",
    }
    CODE_REPOSITORY_BRANCH_FILTER_FIELD: ClassVar[str] = "related_code_repository_branch_uid"

    uid: str = Field(..., description="Public UID of the code repository image")
    title: str | None = Field(None, description="Human-readable image title")
    key: str | None = Field(None, description="Stable image key")
    description: str | None = Field(None, description="Image description")
    code_repository_commit_hash: str = Field(..., description="Canonical full commit SHA for the built image")
    related_code_repository_branch_uid: str | None = Field(
        None,
        description="Public UID of the owning CodeRepositoryBranch",
    )
    source_provenance: CodeRepositoryImageSourceProvenance = Field(
        ...,
        description=(
            "Backend-attested branch, commit, source archive, recipe, and build "
            "identity evidence. Unverified images must be rebuilt before use."
        ),
    )
    base_image: CodeRepositoryBaseImage | None = Field(None, description="Persisted parent base image")
    tags: list[str] | None = Field(
        default=[], description="Observed registry tags for the code repository image"
    )
    build_error: bool = Field(..., description="Whether the backend image build failed")
    is_ready: bool = Field(..., description="Whether the image is ready in Artifact Registry")
    creation_date: datetime.datetime | None = Field(None, description="Creation timestamp")

    @staticmethod
    def _coerce_uid(obj: Any, *, field_name: str) -> str | None:
        if obj is None:
            return None
        if isinstance(obj, UUID):
            return str(obj)
        if isinstance(obj, str):
            normalized = obj.strip()
            if normalized:
                return normalized
        if hasattr(obj, "uid") and obj.uid not in (None, ""):
            return str(obj.uid).strip()
        if isinstance(obj, dict) and obj.get("uid") not in (None, ""):
            return str(obj["uid"]).strip()
        raise TypeError(
            f"{field_name} must be a uid string, an object with .uid, a dict with 'uid', or None. "
            f"Got: {type(obj)!r}"
        )

    @classmethod
    def create(
        cls,
        *,
        code_repository_commit_hash: str,
        related_code_repository_branch_uid: str | CodeRepositoryBranch | dict[str, Any] | None = None,
        base_image_uid: str | CodeRepositoryBaseImage | dict[str, Any] | None = None,
        timeout=None,
        files=None,
        **kwargs,
    ) -> CodeRepositoryImage:
        """
        Create a code repository image.
        """
        payload: dict[str, Any] = {"code_repository_commit_hash": code_repository_commit_hash}

        supplied_code_repository_branch_uid = cls._coerce_uid(
            related_code_repository_branch_uid,
            field_name="related_code_repository_branch_uid",
        )
        from mainsequence.code_repository_context import resolve_code_repository_branch_uid

        payload["related_code_repository_branch_uid"] = resolve_code_repository_branch_uid(
            "CodeRepositoryImage.create",
            supplied_uid=supplied_code_repository_branch_uid,
        )

        image_uid = cls._coerce_uid(base_image_uid, field_name="base_image_uid")
        if image_uid is not None:
            payload["base_image_uid"] = image_uid

        payload.update(kwargs)
        data = cls.serialize_for_json(payload)
        request_payload = {"json": data}
        if files:
            request_payload["files"] = files

        r = make_request(
            s=cls.build_session(),
            loaders=cls.LOADERS,
            r_type="POST",
            url=f"{cls.get_object_url()}/",
            payload=request_payload,
            time_out=timeout,
        )
        if r.status_code not in (200, 201, 202):
            raise_for_response(r, payload=request_payload)
        return cls(**r.json())


class TimeScaleDB(_DataSource):
    database_user: str
    password: str
    host: str
    database_name: str
    port: int

    def get_connection_uri(self):
        password = self.password  # Decrypt password if necessary
        return f"postgresql://{self.database_user}:{password}@{self.host}:{self.port}/{self.database_name}"

    def insert_data_into_table(
        self,
        serialized_data_frame: pd.DataFrame,
        table_update: TimeIndexTableUpdate,
        overwrite: bool,
        time_index_name: str,
        index_names: list,
        grouped_dates: dict,
        column_dtypes_map: Mapping[str, Any] | None = None,
    ):
        from .metatables import TimeIndexTableUpdate

        TimeIndexTableUpdate.post_data_frame_in_chunks(
            serialized_data_frame=serialized_data_frame,
            table_update=table_update,
            data_source=self,
            index_names=index_names,
            time_index_name=time_index_name,
            overwrite=overwrite,
            column_dtypes_map=column_dtypes_map,
        )

    def get_data_by_time_index(
        self,
        table_update: TimeIndexTableUpdate,
        start_date: datetime.datetime | None = None,
        end_date: datetime.datetime | None = None,
        great_or_equal: bool = True,
        less_or_equal: bool = True,
        columns: list[str] | None = None,
        dimension_filters: dict[str, list[Any]] | None = None,
        index_coordinates: list[dict[str, Any]] | None = None,
        dimension_range_map: list[dict[str, Any]] | None = None,
    ) -> pd.DataFrame:
        df = table_update.get_data_between_dates_from_api(
            start_date=start_date,
            end_date=end_date,
            great_or_equal=great_or_equal,
            less_or_equal=less_or_equal,
            dimension_filters=dimension_filters,
            index_coordinates=index_coordinates,
            dimension_range_map=dimension_range_map,
            columns=columns,
        )
        if len(df) == 0:
            if logger:
                logger.warning(f"No data returned from remote API for {table_update.update_hash}")
            return df

        time_index_name, index_names, column_dtypes_map = (
            table_update.output_table._require_time_indexed_table_contract()
        )
        df[time_index_name] = token_to_pandas_series(
            df[time_index_name],
            TIMESTAMP_TZ,
            is_time_index=True,
        )
        for c, c_type in column_dtypes_map.items():
            if c in df.columns:
                df[c] = token_to_pandas_series(
                    df[c],
                    c_type,
                    is_time_index=c == time_index_name,
                )
        df = df.set_index(index_names)
        return df


class DynamicResource(BasePydanticModel, BaseObjectOrm):
    id: int | None = None
    name: str
    type: str
    object_signature: dict
    attributes: dict | None

    created_at: datetime.datetime
    updated_at: datetime.datetime
    is_production: bool
    pod: int

    @classmethod
    def create(self, *args, **kwargs):
        return super().create(*args, **kwargs)


class Bucket(
    CurrentCodeRepositoryEnvironmentResourceMixin,
    ShareableObjectMixin,
    BasePydanticModel,
    BaseObjectOrm,
):
    FILTERSET_FIELDS: ClassVar[dict[str, list[str]]] = {
        "uid": ["in", "exact"],
        "name": ["in", "exact"],
    }
    FILTER_VALUE_NORMALIZERS: ClassVar[dict[str, str]] = {
        "uid": "uid",
        "name": "str",
        "name__in": "str",
    }

    uid: str | None = Field(
        None,
        title="Bucket UID",
        description="Public UID of the bucket.",
        examples=["47b8eac1-7630-44f4-bb42-7b4055ec4afe"],
        json_schema_extra={"label": "Bucket UID"},
    )
    name: str = Field(
        ...,
        title="Bucket Name",
        description="Human-readable Bucket name ",
        examples=["daily_positions_report.pdf"],
        json_schema_extra={"label": "Bucket Name"},
    )
    organization_environment_uid: str | None = Field(
        None,
        description="Read-only UID of the owning Organization Environment.",
    )
    organization_environment_name: str | None = Field(
        None,
        description="Read-only name of the owning Organization Environment.",
    )
    physical_bucket_uid: str | None = Field(
        None,
        description="Read-only UID of the provider-backed physical bucket.",
    )
    backing_ready: bool | None = Field(
        None,
        description="Whether the physical bucket backing is ready for use.",
    )
    backing_last_discovered_at: datetime.datetime | None = Field(
        None,
        description="Last successful physical backing discovery timestamp.",
    )


class Artifact(
    CurrentCodeRepositoryEnvironmentResourceMixin,
    ShareableObjectMixin,
    BasePydanticModel,
    BaseObjectOrm,
):
    uid: str | None = Field(
        None,
        title="Artifact UID",
        description="Public UID of the artifact record.",
        examples=["d28c87b6-a784-4f9f-bc2c-f47b43a04274"],
        json_schema_extra={"label": "Artifact UID"},
    )
    name: str = Field(
        ...,
        title="Artifact Name",
        description="Human-readable artifact name used to identify the stored file or payload.",
        examples=["daily_positions_report.pdf"],
        json_schema_extra={"label": "Artifact Name"},
    )

    bucket_name: str = Field(
        ...,
        title="Bucket Name",
        description="Storage bucket where the artifact content is persisted.",
        examples=["default_bucket"],
        json_schema_extra={"label": "Bucket Name"},
    )
    bucket_uid: str | None = Field(
        None,
        title="Bucket UID",
        description="Public UID of the storage bucket where the artifact content is persisted.",
        examples=["47b8eac1-7630-44f4-bb42-7b4055ec4afe"],
        json_schema_extra={"label": "Bucket UID"},
    )
    content: Any = Field(
        ...,
        title="Artifact Content",
        description="signed url pointed to the download link of the content",
        examples=["<binary-or-serialized-artifact-content>"],
        json_schema_extra={"label": "Artifact Content"},
    )
    creation_date: datetime.datetime = Field(
        ...,
        title="Creation Date",
        description="Timestamp when the artifact was created and stored.",
        examples=["2026-03-15T10:30:00Z"],
        json_schema_extra={"label": "Creation Date"},
    )
    organization_environment_uid: str | None = Field(
        None,
        description="Read-only UID of the owning Organization Environment.",
    )
    organization_environment_name: str | None = Field(
        None,
        description="Read-only name of the owning Organization Environment.",
    )

    @classmethod
    def upload_file(cls, filepath, name, bucket_name=None):
        bucket_name = bucket_name if bucket_name else "default_bucket"
        return cls.get_or_create(
            filepath=filepath,
            name=name,
            bucket_name=bucket_name,
        )

    @classmethod
    def get_or_create(cls, filepath, name, bucket_name):
        url = cls.get_object_url() + "/get-or-create/"
        s = cls.build_session()
        with open(filepath, "rb") as f:
            data = cls._with_sdk_owned_create_context(
                "Artifact.get_or_create",
                {
                    "name": name,
                    "bucket_name": bucket_name if bucket_name else "default_bucket",
                },
            )
            files = {"content": (str(filepath), f, "application/pdf")}
            payload = {"json": data, "files": files}
            r = make_request(s=s, loaders=cls.LOADERS, r_type="POST", url=url, payload=payload)

            if r.status_code not in [200, 201]:
                raise Exception(f"Failed to get artifact: {r.status_code} - {r.text}")

            return cls(**r.json())


def _norm_value(v: Any) -> Any:
    """Normalize values into hashable, deterministic forms for the cache key."""
    # CodeRepository objects → their integer IDs (repository scoped vs global)
    if CodeRepository and isinstance(v, CodeRepository):
        return getattr(v, "id", v)

    # Common iterables → sorted tuples to ignore order in queries like name__in
    if isinstance(v, (set | list | tuple)):
        # Convert nested items too, just in case
        return tuple(sorted(_norm_value(x) for x in v))

    # Dicts → sorted (k,v) tuples
    if isinstance(v, dict):
        return tuple(sorted((k, _norm_value(val)) for k, val in v.items()))

    return v  # primitives pass through


def _norm_kwargs(kwargs: dict[str, Any]) -> tuple[tuple[str, Any], ...]:
    """Stable, hashable key from kwargs (order-insensitive)."""
    items = []
    for k, v in kwargs.items():
        # Special-case a big `name__in` so you don’t produce huge keys.
        if k == "name__in" and isinstance(v, (list | tuple | set)):
            items.append((k, tuple(sorted(str(x) for x in v))))
        else:
            items.append((k, _norm_value(v)))
    return tuple(sorted(items))


class Secret(
    CurrentCodeRepositoryEnvironmentResourceMixin,
    ShareableObjectMixin,
    BasePydanticModel,
    BaseObjectOrm,
):
    FILTERSET_FIELDS: ClassVar[dict[str, list[str]]] = {
        "uid": ["in", "exact"],
        "name": ["in", "exact"],
    }
    FILTER_VALUE_NORMALIZERS: ClassVar[dict[str, str]] = {
        "uid": "uid",
        "name": "str",
        "name__in": "str",
    }

    uid: str | None = Field(None, description="Public uid of the secret.")
    name: str = Field(..., description="Secret name")
    value: SecretStr | None = Field(
        None,
        description="Secret value. The create endpoint may omit it in the response.",
        exclude=True,
    )
    organization_environment_uid: str | None = Field(
        None,
        description="Read-only UID of the owning Organization Environment.",
    )
    organization_environment_name: str | None = Field(
        None,
        description="Read-only name of the owning Organization Environment.",
    )

    @classmethod
    def create(
        cls,
        *,
        name: str,
        value: str,
        timeout: int | None = None,
    ) -> Secret:
        """
        Create a secret.

        Parameters
        ----------
        name:
            Secret name.
        value:
            Secret value. Stored as a string by the backend. The backend create
            response may omit the secret uid and value, so the returned model can
            have `uid=None` and `value=None`.
        timeout:
            Optional request timeout in seconds.
        """
        return super().create(name=name, value=value, timeout=timeout)


class Constant(
    CurrentCodeRepositoryEnvironmentResourceMixin,
    ShareableObjectMixin,
    BasePydanticModel,
    BaseObjectOrm,
):
    """
    Simple organization-level constant.
    """

    FILTERSET_FIELDS: ClassVar[dict[str, list[str]]] = {
        "uid": ["in", "exact"],
        "name": ["in", "exact"],
    }
    FILTER_VALUE_NORMALIZERS: ClassVar[dict[str, str]] = {
        "uid": "uid",
        "name": "str",
        "name__in": "str",
    }

    uid: str | None = Field(None, description="Public UID of the constant.")

    name: str = Field(
        ...,
        max_length=255,
        description="UPPER_SNAKE_CASE; optional category via double-underscore, e.g. 'CURVE__US_TREASURIES'.",
    )
    value: Any = Field(
        ...,
        description="Small JSON value (string/number/bool/object/array). Keep it small (e.g., <=10KB).",
    )
    category: str | None = None
    organization_environment_uid: str | None = Field(
        None,
        description="Read-only UID of the owning Organization Environment.",
    )
    organization_environment_name: str | None = Field(
        None,
        description="Read-only name of the owning Organization Environment.",
    )

    # Class-level cache & lock (Pydantic ignores ClassVar)
    _filter_cache: ClassVar[TTLCache] = TTLCache(maxsize=512, ttl=600)
    _get_cache: ClassVar[TTLCache] = TTLCache(maxsize=1024, ttl=600)

    _cache_lock: ClassVar[RLock] = RLock()

    model_config = dict(from_attributes=True)  # allows .model_validate(from_orm_obj)

    @classmethod
    @cachedmethod(
        lambda cls: cls._filter_cache,  # <- resolves to the real TTLCache
        lock=lambda cls: cls._cache_lock,
        key=lambda cls, **kw: _norm_kwargs(kw),
    )
    def filter(cls, **kwargs):
        # Delegate to your real filter (API/DB) only on cache miss
        return super().filter(**kwargs)

    @classmethod
    @cachedmethod(
        lambda cls: cls._get_cache,
        lock=lambda cls: cls._cache_lock,
        key=lambda cls, **kw: _norm_kwargs(kw),
    )
    def get(cls, **kwargs):
        # Delegate to the API only on a cache miss.
        return super().get(**kwargs)

    @classmethod
    def get_value(cls, name: str):
        return cls.get(name=name).value

    @classmethod
    def create(
        cls,
        *,
        name: str,
        value: Any,
        timeout: int | None = None,
    ) -> Constant:
        """
        Create a constant.

        Parameters
        ----------
        name:
            Constant name in UPPER_SNAKE_CASE. When the name contains `__`,
            the prefix before the first double underscore is used as the
            display category, for example `ASSETS__MASTER`.
        value:
            Small JSON-serializable value.
        timeout:
            Optional request timeout in seconds.
        """
        return super().create(name=name, value=value, timeout=timeout)

    @classmethod
    def invalidate_filter_cache(cls) -> None:
        cls._filter_cache.clear()

    @classmethod
    def create_constants_if_not_exist(cls, constants_to_create: dict):
        # crete global constants if not exist in  backed

        existing_constants = cls.filter(name__in=list(constants_to_create.keys()))
        existing_constants_names = [c.name for c in existing_constants]
        constants_to_register = {
            k: v for k, v in constants_to_create.items() if k not in existing_constants_names
        }
        created_constants = []
        for k, v in constants_to_register.items():
            new_constant = cls.create(name=k, value=v)
            created_constants.append(new_constant)
        return created_constants
