from __future__ import annotations

import datetime
import os
from collections.abc import Mapping
from threading import RLock
from typing import Any, ClassVar
from uuid import UUID

import pandas as pd
import yaml
from cachetools import TTLCache, cachedmethod
from pydantic import Field, SecretStr

from mainsequence.logconf import logger

from .base import BaseObjectOrm, BasePydanticModel, LabelableObjectMixin, ShareableObjectMixin
from .dtype_codec import (
    TIMESTAMP_TZ,
    token_to_pandas_series,
)
from .exceptions import raise_for_response
from .models_metatables import (
    DataSource as _DataSource,
)
from .models_metatables import (
    DynamicTableDataSource as _DynamicTableDataSource,
)
from .utils import (
    MAINSEQUENCE_ENDPOINT,
    loaders,
    make_request,
    session,
)

_default_data_source = None  # Module-level cache

JSON_COMPRESSED_PREFIX = ["json_compressed", "jcomp_"]


class GithubOrganization(BasePydanticModel, BaseObjectOrm):
    uid: str
    login: str
    display_name: str | None = None

    def __str__(self):
        return yaml.safe_dump(self.model_dump(), sort_keys=False, default_flow_style=False)


class ProjectBaseImage(BasePydanticModel, BaseObjectOrm):
    uid: str
    latest_digest: str | None = None
    description: str
    title: str
    tags: list[str] | None = None

    def __str__(self):
        return yaml.safe_dump(self.model_dump(), sort_keys=False, default_flow_style=False)


class ProjectNameValidationNormalized(BasePydanticModel):
    slugified_project_name: str = Field(
        ...,
        title="Slugified Project Name",
        description="Slug-safe project name generated by the platform for URLs and repository naming.",
        examples=["rates-platform"],
        json_schema_extra={"label": "Slugified Project Name"},
    )
    project_library_name: str = Field(
        ...,
        title="Project Library Name",
        description="Python-safe library/module name derived from the proposed project name.",
        examples=["rates_platform"],
        json_schema_extra={"label": "Project Library Name"},
    )


class ProjectNameValidationResult(BasePydanticModel):
    project_name: str = Field(
        ...,
        title="Project Name",
        description="Original project name submitted for validation.",
        examples=["Rates Platform"],
        json_schema_extra={"label": "Project Name"},
    )
    available: bool = Field(
        ...,
        title="Available",
        description="Whether the project name is currently available for creation in the caller's organization.",
        examples=[False],
        json_schema_extra={"label": "Available"},
    )
    reason: str | None = Field(
        None,
        title="Reason",
        description="Human-readable explanation when the requested project name is unavailable or adjusted.",
        examples=["A project with this name already exists in your organization."],
        json_schema_extra={"label": "Reason"},
    )
    normalized: ProjectNameValidationNormalized = Field(
        ...,
        title="Normalized Names",
        description="Platform-generated normalized forms derived from the submitted project name.",
        json_schema_extra={"label": "Normalized Names"},
    )
    suggestions: list[str] = Field(
        default_factory=list,
        title="Suggestions",
        description="Alternative project names suggested by the platform when the submitted name is unavailable.",
        examples=[["Rates Platform 2", "Rates Platform 3", "Rates Platform 4"]],
        json_schema_extra={"label": "Suggestions"},
    )


class ProjectQuickSearchResult(BasePydanticModel):
    uid: str | None = Field(
        None,
        title="UID",
        description="Public uid of the matching project.",
        json_schema_extra={"label": "UID"},
    )
    project_name: str = Field(
        ...,
        title="Project Name",
        description="Display name of the matching project.",
        json_schema_extra={"label": "Project Name"},
    )
    repository_branch: str | None = Field(
        None,
        title="Repository Branch",
        description="Configured repository branch for the matching project.",
        json_schema_extra={"label": "Repository Branch"},
    )
    cluster_uid: str | None = Field(
        None,
        title="Cluster UID",
        description="Public UID of the cluster associated with the matching project, when present.",
        json_schema_extra={"label": "Cluster UID"},
    )


class Project(LabelableObjectMixin, ShareableObjectMixin, BasePydanticModel, BaseObjectOrm):
    FILTERSET_FIELDS: ClassVar[dict[str, list[str]]] = {
        "project_name": ["in", "exact", "contains"],
        "uid": ["in", "exact"],
        "labels": ["exact", "in", "contains"],
    }
    FILTER_VALUE_NORMALIZERS: ClassVar[dict[str, str]] = {
        "uid": "str",
        "uid__in": "str",
        "project_name": "str",
        "labels": "str",
        "labels__in": "str",
        "labels__contains": "str",
    }
    uid: str | None = Field(
        None,
        title="Project UID",
        description="Public uid of the project.",
        examples=["project-uid-142"],
        json_schema_extra={"label": "Project UID"},
    )
    project_name: str = Field(
        ...,
        title="Project Name",
        description="Human-readable name of the project.",
        examples=["Data Research Pipeline"],
        json_schema_extra={"label": "Project Name"},
    )
    data_source: _DynamicTableDataSource | None = Field(
        None,
        title="Data Source",
        description="Default data source associated with the project, when configured.",
        json_schema_extra={"label": "Data Source"},
    )
    git_ssh_url: str | None = Field(
        None,
        title="Git SSH URL",
        description="SSH repository URL used to access the project's source code repository.",
        examples=["git@github.com:mainsequence/data-pipeline.git"],
        json_schema_extra={"label": "Git SSH URL"},
    )
    created_by: str | int | dict[str, Any] | None = Field(
        None,
        title="Created By",
        description="Backend-provided creator metadata for the project.",
        json_schema_extra={"label": "Created By"},
    )

    labels: list[str] = Field(
        default_factory=list,
        title="Labels",
        description=(
            "Organizational labels attached to the project. "
            "These are helpers for grouping and discovery only and do not change runtime behavior or functionality."
        ),
        json_schema_extra={"label": "Labels"},
    )

    is_initialized: bool = Field(
        ...,
        title="Is Initialized",
        description="Whether the project has completed its initial setup and is ready for use.",
        examples=[True],
        json_schema_extra={"label": "Is Initialized"},
    )

    @staticmethod
    def _normalize_env_vars(
        env_vars: dict[str, str] | list[dict[str, str]] | None,
    ) -> list[dict[str, str]] | None:
        """
        Serializer expects: [{"name": "...", "value": "..."}, ...]
        Allow passing a dict for convenience.
        """
        if env_vars is None:
            return None
        if isinstance(env_vars, dict):
            return [{"name": k, "value": v} for k, v in env_vars.items()]
        # assume already list-of-dicts shape
        return env_vars

    @staticmethod
    def _coerce_uid(obj: Any, *, field_name: str) -> str | None:
        """
        Accept:
          - None
          - uid string
          - any object with attribute `.uid`
          - dict-like with key "uid"
        """
        if obj is None:
            return None
        if isinstance(obj, UUID):
            return str(obj)
        if isinstance(obj, str):
            normalized = obj.strip()
            if normalized:
                return normalized
        if hasattr(obj, "uid") and obj.uid not in (None, ""):
            return str(obj.uid).strip()
        if isinstance(obj, dict) and obj.get("uid") not in (None, ""):
            return str(obj["uid"]).strip()
        raise TypeError(
            f"{field_name} must be a uid string, an object with .uid, a dict with 'uid', or None. "
            f"Got: {type(obj)!r}"
        )

    @classmethod
    def create(
        cls,
        *,
        project_name: str,
        data_source_uid: str | _DynamicTableDataSource | dict[str, Any] | None = None,
        default_base_image_uid: str | ProjectBaseImage | dict[str, Any] | None = None,
        github_org_uid: str | GithubOrganization | dict[str, Any] | None = None,
        repository_branch: str | None = None,
        env_vars: dict[str, str] | list[dict[str, str]] | None = None,
        timeout: int | None = None,
    ) -> Project:
        """
        POST /projects/

        Sends:
          - project_name
          - repository_branch (optional)
          - data_source_uid (optional; server may auto-pick for individual orgs)
          - default_base_image_uid (optional)
          - github_org_uid (optional)
          - env_vars (optional list of {name,value})
        """
        url = cls.get_object_url() + "/"

        payload: dict[str, Any] = {
            "project_name": project_name,
        }

        if repository_branch:
            payload["repository_branch"] = repository_branch

        ds_uid = cls._coerce_uid(data_source_uid, field_name="data_source_uid")
        if ds_uid is not None:
            payload["data_source_uid"] = ds_uid

        img_uid = cls._coerce_uid(default_base_image_uid, field_name="default_base_image_uid")
        if img_uid is not None:
            payload["default_base_image_uid"] = img_uid

        org_uid = cls._coerce_uid(github_org_uid, field_name="github_org_uid")
        if org_uid is not None:
            payload["github_org_uid"] = org_uid

        env_list = cls._normalize_env_vars(env_vars)
        if env_list is not None:
            payload["env_vars"] = env_list

        s = cls.build_session()
        r = make_request(
            s=s,
            loaders=cls.LOADERS,
            r_type="POST",
            url=url,
            payload={"json": payload},
            time_out=timeout,
        )

        # your helpers already exist; use them consistently
        raise_for_response(r)

        # DRF should return 201 with your detail serializer shape
        return cls(**r.json())

    @classmethod
    def get_user_default_project(cls):
        url = cls.get_object_url() + "/get_user_default_project/"

        s = cls.build_session()
        r = make_request(
            s=s,
            loaders=cls.LOADERS,
            r_type="GET",
            url=url,
        )
        if r.status_code == 404:
            raise_for_response(
                r,
            )

        if r.status_code != 200:
            raise Exception(f"Error in request {r.text}")
        return cls(**r.json())

    @classmethod
    def quick_search(
        cls,
        q: str,
        *,
        limit: int = 20,
        timeout: int | None = None,
    ) -> list[ProjectQuickSearchResult]:
        """
        Return project quick-search matches visible to the authenticated user.

        This hits:
            GET /orm/api/pods/projects/quick-search/?q=...

        Parameters
        ----------
        q:
            Search query. Must contain at least 3 non-whitespace characters.
        limit:
            Maximum number of matches to return. Defaults to 20 and is capped at 100.
        timeout:
            Optional request timeout in seconds.
        """
        normalized_query = (q or "").strip()
        if len(normalized_query) < 3:
            raise ValueError("Query must contain at least 3 characters.")

        limit = int(limit)
        if limit < 1 or limit > 100:
            raise ValueError("limit must be between 1 and 100")

        url = cls.get_object_url() + "/quick-search/"
        r = make_request(
            s=cls.build_session(),
            loaders=cls.LOADERS,
            r_type="GET",
            url=url,
            payload={"params": {"q": normalized_query, "limit": limit}},
            time_out=timeout,
        )
        raise_for_response(r)

        if not r.content:
            return []

        payload = r.json()
        if not isinstance(payload, list):
            raise ValueError(
                f"Unexpected response type for Project.quick_search(): {type(payload)!r}"
            )

        return [ProjectQuickSearchResult.model_validate(item) for item in payload]

    @classmethod
    def validate_name(
        cls,
        *,
        project_name: str,
        timeout: int | None = None,
    ) -> ProjectNameValidationResult:
        """
        Validate whether a project name is available for creation on the platform.

        This hits:
            GET /orm/api/pods/projects/validate-name/?project_name=...

        Parameters
        ----------
        project_name:
            Candidate project name to validate.
        timeout:
            Optional request timeout in seconds.

        Returns
        -------
        ProjectNameValidationResult
            Validation payload including availability, normalized names, and suggested alternatives.
        """
        normalized_project_name = (project_name or "").strip()
        if not normalized_project_name:
            raise ValueError("project_name is required.")

        url = cls.get_object_url() + "/validate-name/"
        r = make_request(
            s=cls.build_session(),
            loaders=cls.LOADERS,
            r_type="GET",
            url=url,
            payload={"params": {"project_name": normalized_project_name}},
            time_out=timeout,
        )
        raise_for_response(r)

        if not r.content:
            raise ValueError("Project.validate_name() returned an empty response.")

        payload = r.json()
        if not isinstance(payload, dict):
            raise ValueError(
                f"Unexpected response type for Project.validate_name(): {type(payload)!r}"
            )

        return ProjectNameValidationResult.model_validate(payload)

    @classmethod
    def sync_project_after_commit(
        cls,
        project_uid: str | int,
        timeout: int | None = None,
    ) -> Project | dict[str, Any] | None:
        url = f"{cls.get_object_url()}/{project_uid}/sync_project_after_commit/"

        s = cls.build_session()
        r = make_request(
            s=s,
            loaders=cls.LOADERS,
            r_type="POST",
            url=url,
            time_out=timeout,
        )
        raise_for_response(r)

        if not r.content:
            return None

        data = r.json()
        if isinstance(data, dict) and ({"project_name"} <= set(data.keys())):
            return cls(**data)
        return data

    def delete(
        self,
        *,
        delete_repositories: bool = False,
        timeout: int | None = None,
    ) -> dict[str, Any] | None:
        """
        DELETE /projects/{uid}/

        Optional query param:
          - delete_repositories=true
        """
        cls = type(self)
        url = f"{cls.get_object_url()}/{self._public_detail_reference()}/"

        request_payload: dict[str, Any] = {}
        if delete_repositories:
            request_payload["params"] = {"delete_repositories": "true"}

        s = cls.build_session()
        r = make_request(
            s=s,
            loaders=cls.LOADERS,
            r_type="DELETE",
            url=url,
            payload=request_payload,
            time_out=timeout,
        )

        raise_for_response(r)

        return r.json() if r.content else None

    def get_data_nodes_updates(self, *, timeout: int | None = None) -> list[Any]:
        """
        GET /projects/{uid}/get-data-nodes-updates/

        Returns a list of DataNodeUpdate objects for this project.
        """
        from .models_metatables import DataNodeUpdate

        cls = type(self)
        url = f"{cls.get_object_url()}/{self._public_detail_reference()}/get-data-nodes-updates/"

        s = cls.build_session()
        r = make_request(
            s=s,
            loaders=cls.LOADERS,
            r_type="GET",
            url=url,
            time_out=timeout,
        )
        raise_for_response(r)

        payload = r.json()
        if isinstance(payload, list):
            raw_updates = payload
        elif isinstance(payload, dict):
            if isinstance(payload.get("results"), list):
                raw_updates = payload["results"]
            elif isinstance(payload.get("data_node_updates"), list):
                raw_updates = payload["data_node_updates"]
            else:
                raw_updates = []
        else:
            raise ValueError(
                f"Unexpected response type for project data node updates: {type(payload)!r}"
            )

        return [u if isinstance(u, DataNodeUpdate) else DataNodeUpdate(**u) for u in raw_updates]

    def __str__(self):
        return yaml.safe_dump(
            self.model_dump(),
            sort_keys=False,
            default_flow_style=False,
        )


class ProjectImage(BasePydanticModel, BaseObjectOrm):
    """
    Image build from a a project
    """

    FILTERSET_FIELDS: ClassVar[dict[str, list[str]]] = {
        "search": ["exact"],
        "related_project__uid": ["in", "exact"],
        "related_project_uid": ["in", "exact"],
        "project_repo_hash": ["exact", "in"],
    }
    FILTER_VALUE_NORMALIZERS: ClassVar[dict[str, str]] = {
        "related_project__uid": "uid",
        "related_project_uid": "uid",
    }

    uid: str = Field(..., description="Public UID of the project image")
    title: str | None = Field(None, description="Human-readable image title")
    key: str | None = Field(None, description="Stable image key")
    description: str | None = Field(None, description="Image description")
    project_repo_hash: str = Field(..., description="Canonical full commit SHA for the built image")
    related_project_uid: str | None = Field(None, description="Public UID of the owning project")
    base_image: ProjectBaseImage | None = Field(None, description="Persisted parent base image")
    tags: list[str] | None = Field(
        default=[], description="Observed registry tags for the project image"
    )
    build_error: str | None = Field(None, description="Backend build error, when present")
    is_ready: bool = Field(..., description="Whether the image is ready in Artifact Registry")
    creation_date: datetime.datetime | None = Field(None, description="Creation timestamp")

    @staticmethod
    def _coerce_uid(obj: Any, *, field_name: str) -> str | None:
        if obj is None:
            return None
        if isinstance(obj, UUID):
            return str(obj)
        if isinstance(obj, str):
            normalized = obj.strip()
            if normalized:
                return normalized
        if hasattr(obj, "uid") and obj.uid not in (None, ""):
            return str(obj.uid).strip()
        if isinstance(obj, dict) and obj.get("uid") not in (None, ""):
            return str(obj["uid"]).strip()
        raise TypeError(
            f"{field_name} must be a uid string, an object with .uid, a dict with 'uid', or None. "
            f"Got: {type(obj)!r}"
        )

    @classmethod
    def create(
        cls,
        *,
        project_repo_hash: str,
        related_project_uid: str | Project | dict[str, Any] | None = None,
        base_image_uid: str | ProjectBaseImage | dict[str, Any] | None = None,
        timeout=None,
        files=None,
        **kwargs,
    ) -> ProjectImage:
        """
        Create a project image.
        """
        payload: dict[str, Any] = {"project_repo_hash": project_repo_hash}

        project_uid = cls._coerce_uid(related_project_uid, field_name="related_project_uid")
        if project_uid is not None:
            payload["related_project_uid"] = project_uid

        image_uid = cls._coerce_uid(base_image_uid, field_name="base_image_uid")
        if image_uid is not None:
            payload["base_image_uid"] = image_uid

        payload.update(kwargs)
        data = cls.serialize_for_json(payload)
        request_payload = {"json": data}
        if files:
            request_payload["files"] = files

        r = make_request(
            s=cls.build_session(),
            loaders=cls.LOADERS,
            r_type="POST",
            url=f"{cls.get_object_url()}/",
            payload=request_payload,
            time_out=timeout,
        )
        if r.status_code not in (200, 201, 202):
            raise_for_response(r, payload=request_payload)
        return cls(**r.json())


class TimeScaleDB(_DataSource):
    database_user: str
    password: str
    host: str
    database_name: str
    port: int

    def get_connection_uri(self):
        password = self.password  # Decrypt password if necessary
        return f"postgresql://{self.database_user}:{password}@{self.host}:{self.port}/{self.database_name}"

    def insert_data_into_table(
        self,
        serialized_data_frame: pd.DataFrame,
        data_node_update: DataNodeUpdate,
        overwrite: bool,
        time_index_name: str,
        index_names: list,
        grouped_dates: dict,
        column_dtypes_map: Mapping[str, Any] | None = None,
    ):
        from .models_metatables import DataNodeUpdate

        DataNodeUpdate.post_data_frame_in_chunks(
            serialized_data_frame=serialized_data_frame,
            data_node_update=data_node_update,
            data_source=self,
            index_names=index_names,
            time_index_name=time_index_name,
            overwrite=overwrite,
            column_dtypes_map=column_dtypes_map,
        )

    def get_data_by_time_index(
        self,
        data_node_update: DataNodeUpdate,
        start_date: datetime.datetime | None = None,
        end_date: datetime.datetime | None = None,
        great_or_equal: bool = True,
        less_or_equal: bool = True,
        columns: list[str] | None = None,
        dimension_filters: dict[str, list[Any]] | None = None,
        index_coordinates: list[dict[str, Any]] | None = None,
        dimension_range_map: list[dict[str, Any]] | None = None,
    ) -> pd.DataFrame:
        df = data_node_update.get_data_between_dates_from_api(
            start_date=start_date,
            end_date=end_date,
            great_or_equal=great_or_equal,
            less_or_equal=less_or_equal,
            dimension_filters=dimension_filters,
            index_coordinates=index_coordinates,
            dimension_range_map=dimension_range_map,
            columns=columns,
        )
        if len(df) == 0:
            if logger:
                logger.warning(
                    f"No data returned from remote API for {data_node_update.update_hash}"
                )
            return df

        time_index_name, index_names, column_dtypes_map = (
            data_node_update.data_node_storage._require_time_indexed_table_contract()
        )
        df[time_index_name] = token_to_pandas_series(
            df[time_index_name],
            TIMESTAMP_TZ,
            is_time_index=True,
        )
        for c, c_type in column_dtypes_map.items():
            if c in df.columns:
                df[c] = token_to_pandas_series(
                    df[c],
                    c_type,
                    is_time_index=c == time_index_name,
                )
        df = df.set_index(index_names)
        return df


class DynamicResource(BasePydanticModel, BaseObjectOrm):
    id: int | None = None
    name: str
    type: str
    object_signature: dict
    attributes: dict | None

    created_at: datetime.datetime
    updated_at: datetime.datetime
    is_production: bool
    pod: int

    @classmethod
    def create(self, *args, **kwargs):
        return super().create(*args, **kwargs)


def query_agent(json_payload: dict, timeout=None):
    url = MAINSEQUENCE_ENDPOINT + "/orm/api/tdag-gpt/query_agent/"
    r = make_request(
        s=session,
        r_type="POST",
        url=url,
        payload={"json": json_payload},
        loaders=loaders,
        time_out=(timeout if timeout is not None else 200),
    )
    from .exceptions import raise_for_response

    raise_for_response(r, payload={"json": json_payload})
    return r


def add_created_object_to_jobrun(
    model_name: str, app_label: str, object_id: int, timeout: int | None = None
) -> dict:
    """
    Logs a new object that was created by this JobRun instance.

    Args:
        model_name: The string name of the created model (e.g., "Project").
        app_label: The Django app label where the model is defined (e.g., "pod_manager").
        object_id: The primary key of the created object instance.
        timeout: Optional request timeout in seconds.

    Returns:
        A dictionary representing the created record.
    """
    url = (
        MAINSEQUENCE_ENDPOINT
        + f"/orm/api/pods/job-run/{os.getenv('JOB_RUN_ID')}/add_created_object/"
    )
    payload = {"json": {"app_label": app_label, "model_name": model_name, "object_id": object_id}}

    r = make_request(
        s=session,
        loaders=loaders,
        r_type="POST",
        url=url,
        payload=payload,
        time_out=timeout,
    )

    from .exceptions import raise_for_response

    raise_for_response(r, payload=payload)
    return r.json()


class Bucket(ShareableObjectMixin, BasePydanticModel, BaseObjectOrm):
    FILTERSET_FIELDS: ClassVar[dict[str, list[str]]] = {
        "uid": ["in", "exact"],
        "name": ["in", "exact"],
    }
    FILTER_VALUE_NORMALIZERS: ClassVar[dict[str, str]] = {
        "uid": "uid",
        "name": "str",
        "name__in": "str",
    }

    uid: str | None = Field(
        None,
        title="Bucket UID",
        description="Public UID of the bucket.",
        examples=["47b8eac1-7630-44f4-bb42-7b4055ec4afe"],
        json_schema_extra={"label": "Bucket UID"},
    )
    name: str = Field(
        ...,
        title="Bucket Name",
        description="Human-readable Bucket name ",
        examples=["daily_positions_report.pdf"],
        json_schema_extra={"label": "Bucket Name"},
    )


class Artifact(ShareableObjectMixin, BasePydanticModel, BaseObjectOrm):
    uid: str | None = Field(
        None,
        title="Artifact UID",
        description="Public UID of the artifact record.",
        examples=["d28c87b6-a784-4f9f-bc2c-f47b43a04274"],
        json_schema_extra={"label": "Artifact UID"},
    )
    name: str = Field(
        ...,
        title="Artifact Name",
        description="Human-readable artifact name used to identify the stored file or payload.",
        examples=["daily_positions_report.pdf"],
        json_schema_extra={"label": "Artifact Name"},
    )

    bucket_name: str = Field(
        ...,
        title="Bucket Name",
        description="Storage bucket where the artifact content is persisted.",
        examples=["default_bucket"],
        json_schema_extra={"label": "Bucket Name"},
    )
    bucket_uid: str | None = Field(
        None,
        title="Bucket UID",
        description="Public UID of the storage bucket where the artifact content is persisted.",
        examples=["47b8eac1-7630-44f4-bb42-7b4055ec4afe"],
        json_schema_extra={"label": "Bucket UID"},
    )
    content: Any = Field(
        ...,
        title="Artifact Content",
        description="signed url pointed to the download link of the content",
        examples=["<binary-or-serialized-artifact-content>"],
        json_schema_extra={"label": "Artifact Content"},
    )
    creation_date: datetime.datetime = Field(
        ...,
        title="Creation Date",
        description="Timestamp when the artifact was created and stored.",
        examples=["2026-03-15T10:30:00Z"],
        json_schema_extra={"label": "Creation Date"},
    )

    @classmethod
    def upload_file(cls, filepath, name, bucket_name=None):
        bucket_name = bucket_name if bucket_name else "default_bucket"
        return cls.get_or_create(
            filepath=filepath,
            name=name,
            bucket_name=bucket_name,
        )

    @classmethod
    def get_or_create(cls, filepath, name, bucket_name):
        url = cls.get_object_url() + "/get_or_create/"
        s = cls.build_session()
        with open(filepath, "rb") as f:
            data = {
                "name": name,
                "bucket_name": bucket_name if bucket_name else "default_bucket",
            }
            files = {"content": (str(filepath), f, "application/pdf")}
            payload = {"json": data, "files": files}
            r = make_request(s=s, loaders=cls.LOADERS, r_type="POST", url=url, payload=payload)

            if r.status_code not in [200, 201]:
                raise Exception(f"Failed to get artifact: {r.status_code} - {r.text}")

            return cls(**r.json())


def _norm_value(v: Any) -> Any:
    """Normalize values into hashable, deterministic forms for the cache key."""
    # Project objects → their integer IDs (project scoped vs global)
    if Project and isinstance(v, Project):
        return getattr(v, "id", v)

    # Common iterables → sorted tuples to ignore order in queries like name__in
    if isinstance(v, (set | list | tuple)):
        # Convert nested items too, just in case
        return tuple(sorted(_norm_value(x) for x in v))

    # Dicts → sorted (k,v) tuples
    if isinstance(v, dict):
        return tuple(sorted((k, _norm_value(val)) for k, val in v.items()))

    return v  # primitives pass through


def _norm_kwargs(kwargs: dict[str, Any]) -> tuple[tuple[str, Any], ...]:
    """Stable, hashable key from kwargs (order-insensitive)."""
    items = []
    for k, v in kwargs.items():
        # Special-case a big `name__in` so you don’t produce huge keys.
        if k == "name__in" and isinstance(v, (list | tuple | set)):
            items.append((k, tuple(sorted(str(x) for x in v))))
        else:
            items.append((k, _norm_value(v)))
    return tuple(sorted(items))


class Secret(ShareableObjectMixin, BasePydanticModel, BaseObjectOrm):
    FILTERSET_FIELDS: ClassVar[dict[str, list[str]]] = {
        "uid": ["in", "exact"],
        "name": ["in", "exact"],
    }
    FILTER_VALUE_NORMALIZERS: ClassVar[dict[str, str]] = {
        "uid": "uid",
        "name": "str",
        "name__in": "str",
    }

    uid: str | None = Field(None, description="Public uid of the secret.")
    name: str = Field(..., description="Secret name")
    value: SecretStr | None = Field(
        None,
        description="Secret value. The create endpoint may omit it in the response.",
        exclude=True,
    )

    @classmethod
    def create(
        cls,
        *,
        name: str,
        value: str,
        timeout: int | None = None,
    ) -> Secret:
        """
        Create a secret.

        Parameters
        ----------
        name:
            Secret name.
        value:
            Secret value. Stored as a string by the backend. The backend create
            response may omit the secret uid and value, so the returned model can
            have `uid=None` and `value=None`.
        timeout:
            Optional request timeout in seconds.
        """
        return super().create(name=name, value=value, timeout=timeout)


class Constant(ShareableObjectMixin, BasePydanticModel, BaseObjectOrm):
    """
    Simple organization-level constant.
    """

    FILTERSET_FIELDS: ClassVar[dict[str, list[str]]] = {
        "uid": ["in", "exact"],
        "name": ["in", "exact"],
    }
    FILTER_VALUE_NORMALIZERS: ClassVar[dict[str, str]] = {
        "uid": "uid",
        "name": "str",
        "name__in": "str",
    }

    uid: str | None = Field(None, description="Public UID of the constant.")

    name: str = Field(
        ...,
        max_length=255,
        description="UPPER_SNAKE_CASE; optional category via double-underscore, e.g. 'CURVE__US_TREASURIES'.",
    )
    value: Any = Field(
        ...,
        description="Small JSON value (string/number/bool/object/array). Keep it small (e.g., <=10KB).",
    )
    category: str | None = None

    # Class-level cache & lock (Pydantic ignores ClassVar)
    _filter_cache: ClassVar[TTLCache] = TTLCache(maxsize=512, ttl=600)
    _get_cache: ClassVar[TTLCache] = TTLCache(maxsize=1024, ttl=600)

    _cache_lock: ClassVar[RLock] = RLock()

    model_config = dict(from_attributes=True)  # allows .model_validate(from_orm_obj)

    @classmethod
    @cachedmethod(
        lambda cls: cls._filter_cache,  # <- resolves to the real TTLCache
        lock=lambda cls: cls._cache_lock,
        key=lambda cls, **kw: _norm_kwargs(kw),
    )
    def filter(cls, **kwargs):
        # Delegate to your real filter (API/DB) only on cache miss
        return super().filter(**kwargs)

    @classmethod
    @cachedmethod(
        lambda cls: cls._get_cache,
        lock=lambda cls: cls._cache_lock,
        key=lambda cls, **kw: _norm_kwargs(kw),
    )
    def get(cls, **kwargs):
        # e.g. get(name="CURVE__M_BONOS", project=None)
        return super().get(**kwargs)

    @classmethod
    def get_value(cls, name: str):
        return cls.get(name=name).value

    @classmethod
    def create(
        cls,
        *,
        name: str,
        value: Any,
        timeout: int | None = None,
    ) -> Constant:
        """
        Create a constant.

        Parameters
        ----------
        name:
            Constant name in UPPER_SNAKE_CASE. When the name contains `__`,
            the prefix before the first double underscore is used as the
            display category, for example `ASSETS__MASTER`.
        value:
            Small JSON-serializable value.
        timeout:
            Optional request timeout in seconds.
        """
        return super().create(name=name, value=value, timeout=timeout)

    @classmethod
    def invalidate_filter_cache(cls) -> None:
        cls._filter_cache.clear()

    @classmethod
    def create_constants_if_not_exist(cls, constants_to_create: dict):
        # crete global constants if not exist in  backed

        existing_constants = cls.filter(name__in=list(constants_to_create.keys()))
        existing_constants_names = [c.name for c in existing_constants]
        constants_to_register = {
            k: v for k, v in constants_to_create.items() if k not in existing_constants_names
        }
        created_constants = []
        for k, v in constants_to_register.items():
            new_constant = cls.create(name=k, value=v)
            created_constants.append(new_constant)
        return created_constants


from . import models_metatables as _models_metatables

_models_metatables.SessionDataSource.set_remote_db()
