name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # --- START OF THE FIX ---
      # Instead of using a requirements.txt file, we install the
      # documentation-specific packages directly here.
      - name: Install MkDocs and plugins
        run: |
          pip install \
            mkdocs-material \
            mkdocs-gen-files \
            mkdocs-literate-nav \
            mkdocs-autorefs \
            mkdocs-mermaid2-plugin \
            mkdocstrings[python]
      # --- END OF THE FIX ---

      - name: Build MkDocs site
        run: mkdocs build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4