name: Deploy MkDocs Documentation

on:
  push:
    tags:
      - 'v*'   # only run on version tags (e.g. v1.2.3)

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-docs:
    # extra safety so it never runs on non-tag refs
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MkDocs and plugins
        run: |
          pip install \
            mkdocs-material \
            mkdocs-gen-files \
            mkdocs-literate-nav \
            mkdocs-autorefs \
            mkdocs-mermaid2-plugin \
            'mkdocstrings[python]'

      - name: Build MkDocs site
        run: mkdocs build

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - id: deployment
        uses: actions/deploy-pages@v4
